name: deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: 
      name: deploy    
    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd ${{ secrets.PATH }}
          git pull
          yarn install && pm2 restart /root/.pm2/pm2.json --only odd-taxi